import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Listen for incoming Push Events from the server
self.addEventListener('push', event => {
  const data = event.data ? event.data.json() : {}
  const title = data.title || 'ClimateAI Alert'
  const options = {
    body: data.body || 'A new alert has been issued for your tracked location.',
    icon: '/logo.png',
    badge: '/favicon.svg', // Small monochrome icon for the status bar
    vibrate: [200, 100, 200, 100, 200, 100, 200], // Emergency vibration pattern
    data: {
      url: 'http://localhost:3000/alerts'
    }
  }

  event.waitUntil(self.registration.showNotification(title, options))
})

// Handle Notification Clicks (Route user to the Alerts dashboard)
self.addEventListener('notificationclick', event => {
  event.notification.close()
  if (event.notification.data && event.notification.data.url) {
    event.waitUntil(
      clients.matchAll({ type: 'window' }).then(windowClients => {
        // If app is already open, focus it
        for (let i = 0; i < windowClients.length; i++) {
          const client = windowClients[i]
          if (client.url.includes('/alerts') && 'focus' in client) {
            return client.focus()
          }
        }
        // Otherwise open a new window
        if (clients.openWindow) {
          return clients.openWindow(event.notification.data.url)
        }
      })
    )
  }
})
